version: '3'

services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
    networks:
      my-macvlan-net:
        ipv4_address: 192.168.1.200
  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
    networks:
      my-macvlan-net:
        ipv4_address: 192.168.1.201
  cassandra3:
    image: cassandra:latest
    container_name: cassandra3
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
    networks:
      my-macvlan-net:
        ipv4_address: 192.168.1.202

networks:
  my-macvlan-net:
    name: 'my-macvlan-net'
    external: 'true'
